@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Mon Jun 13 10:19:11 +0300 2022
REM SW Build 3064766 on Wed Nov 18 09:12:45 MST 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim Top_Level_Datapath_tb_behav -key {Behavioral:sim_1:Functional:Top_Level_Datapath_tb} -tclbatch Top_Level_Datapath_tb.tcl -view C:/Users/SFG/Desktop/Digital_Design_Project/Top_Level_Datapath/Top_Level_Datapath_tb_func_synth1.wcfg -log simulate.log"
call xsim  Top_Level_Datapath_tb_behav -key {Behavioral:sim_1:Functional:Top_Level_Datapath_tb} -tclbatch Top_Level_Datapath_tb.tcl -view C:/Users/SFG/Desktop/Digital_Design_Project/Top_Level_Datapath/Top_Level_Datapath_tb_func_synth1.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
